version: '3'

services:
    mysqldb:  
      image: mysql:8.0.2
      ports:
        - "3306:3306"
      environment:
       - MYSQL_DATABASE=fredbetdb
       - MYSQL_ROOT_PASSWORD=secred
       - MYSQL_USER=fred
       - MYSQL_PASSWORD=fred
      networks:
       - default
    fredbet:
      image: fred4jupiter/fredbet:latest
      links:
        - mysqldb
      depends_on:
        - mysqldb
      ports:
        - "8081:8080"
      environment:
       - SPRING_PROFILES_ACTIVE=prod
       - SPRING_DATASOURCE_HIKARI_JDBC_URL=jdbc:mysql://mysqldb:3306/fredbetdb
       - SPRING_DATASOURCE_HIKARI_USERNAME=fred
       - SPRING_DATASOURCE_HIKARI_PASSWORD=fred
       - SPRING_DATASOURCE_HIKARI_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver
       - FREDBET_IMAGE_LOCATION_FILE=FILE_SYSTEM
       - FREDBET_IMAGE_FILE_SYSTEM_BASE_FOLDER=/home/fred/fredbet_images
      volumes:
       - "~/fredbet_images:/home/fred/fredbet_images"
      networks:
       - default

networks:
 default:
