spring:
  thymeleaf:
    cache: false
  h2:
    console:
      # connect in console (http://localhost:8080/console) with jdbcUrl: jdbc:h2:mem:testdb
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:~/fredbetdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

fredbet:
  create-demo-data: false